# Generated by Django 4.2.3 on 2023-07-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_conta_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('IT', 'Itaú'), ('SA', 'Santander'), ('BB', 'Banco do Brasil'), ('BD', 'Bradesco')], max_length=2),
        ),
    ]
